apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ouu9m0fed-nodejs
  janus-idp.io/tekton: ouu9m0fed-nodejs
  backstage.io/kubernetes-id: ouu9m0fed-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ouu9m0fed-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
