apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ouu9m0fed-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ouu9m0fed-nodejs 
  name: ouu9m0fed-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ouu9m0fed-nodejs 
